/**
 * Database Schema Definitions
 * Simple field structure and default values for all tables
 */

const dbSchema = {
  // ============================================================
  // PARTNERS TABLE
  // ============================================================
  partners: {
    required: ['user_id'],
    fields: {
      // id: UUID (auto-generated by db)
      user_id: { type: 'text', required: true, unique: true },
      name: { type: 'text', required: false, default: null },
      email: { type: 'text', required: false, default: null },
      company: { type: 'text', required: false, default: null },
      // created_at: TIMESTAMPTZ (auto-generated by db)
    }
  },

  // ============================================================
  // CONNECTED_PAGES TABLE
  // ============================================================
  connected_pages: {
    required: ['partner_id', 'fb_page_id'],
    fields: {
      // id: UUID (auto-generated by db)
      partner_id: { type: 'uuid', required: true },
      fb_page_id: { type: 'text', required: true },
      page_name: { type: 'text', required: false, default: null },
      page_token_encrypted: { type: 'text', required: false, default: null },
      fan_count: { type: 'bigint', required: false, default: 0 },
      is_active: { type: 'boolean', required: false, default: true },
      last_synced_at: { type: 'timestamptz', required: false, default: null },
      // created_at: TIMESTAMPTZ (auto-generated by db)
    }
  },

  // ============================================================
  // POSTS TABLE
  // ============================================================
  posts: {
    required: ['page_id', 'fb_post_id'],
    fields: {
      // id: UUID (auto-generated by db)
      page_id: { type: 'uuid', required: true },
      fb_post_id: { type: 'text', required: true },
      message: { type: 'text', required: false, default: null },
      type: { type: 'text', required: false, default: null }, // status, link, photo, video, etc.
      permalink: { type: 'text', required: false, default: null },
      created_time: { type: 'timestamptz', required: false, default: null },
      // synced_at: TIMESTAMPTZ (auto-generated by db)
    }
  },

  // ============================================================
  // PAGE_INSIGHTS TABLE
  // ============================================================
  page_insights: {
    required: ['page_id', 'metric_name'],
    fields: {
      // id: UUID (auto-generated by db)
      page_id: { type: 'uuid', required: true },
      metric_name: { type: 'text', required: true }, // e.g., 'page_impressions', 'page_fans'
      metric_value: { type: 'jsonb', required: false, default: null },
      period: { type: 'text', required: false, default: null }, // day, week, month, lifetime
      end_time: { type: 'timestamptz', required: false, default: null },
      // synced_at: TIMESTAMPTZ (auto-generated by db)
    }
  },

  // ============================================================
  // POST_INSIGHTS TABLE
  // ============================================================
  post_insights: {
    required: ['post_id', 'metric_name'],
    fields: {
      // id: UUID (auto-generated by db)
      post_id: { type: 'uuid', required: true },
      metric_name: { type: 'text', required: true }, // e.g., 'post_impressions', 'post_engagement'
      metric_value: { type: 'jsonb', required: false, default: null },
      period: { type: 'text', required: false, default: null },
      end_time: { type: 'timestamptz', required: false, default: null },
      // synced_at: TIMESTAMPTZ (auto-generated by db)
    }
  },

  // ============================================================
  // CM_EARNINGS_POST TABLE
  // ============================================================
  cm_earnings_post: {
    required: ['post_id'],
    fields: {
      // id: UUID (auto-generated by db)
      post_id: { type: 'uuid', required: true },
      earnings_amount: { type: 'numeric', required: false, default: 0 },
      approximate_earnings: { type: 'numeric', required: false, default: 0 },
      currency: { type: 'text', required: false, default: 'USD' },
      period: { type: 'text', required: false, default: null },
      end_time: { type: 'timestamptz', required: false, default: null },
      // synced_at: TIMESTAMPTZ (auto-generated by db)
    }
  },

  // ============================================================
  // CM_EARNINGS_PAGE TABLE
  // ============================================================
  cm_earnings_page: {
    required: ['page_id'],
    fields: {
      // id: UUID (auto-generated by db)
      page_id: { type: 'uuid', required: true },
      earnings_amount: { type: 'numeric', required: false, default: 0 },
      approximate_earnings: { type: 'numeric', required: false, default: 0 },
      content_type_breakdown: { type: 'jsonb', required: false, default: null },
      currency: { type: 'text', required: false, default: 'USD' },
      period: { type: 'text', required: false, default: null },
      end_time: { type: 'timestamptz', required: false, default: null },
      // synced_at: TIMESTAMPTZ (auto-generated by db)
    }
  },

  // ============================================================
  // THIRD_PARTY_DATA TABLE
  // ============================================================
  third_party_data: {
    required: ['data_type'],
    fields: {
      // id: UUID (auto-generated by db)
      page_id: { type: 'uuid', required: false, default: null },
      post_id: { type: 'uuid', required: false, default: null },
      data_type: { type: 'text', required: true }, // stars | bonus | payout
      value: { type: 'jsonb', required: false, default: null },
      // synced_at: TIMESTAMPTZ (auto-generated by db)
    }
  },

  // ============================================================
  // SYNC_JOBS TABLE
  // ============================================================
  sync_jobs: {
    required: ['page_id', 'job_type'],
    fields: {
      // id: UUID (auto-generated by db)
      page_id: { type: 'uuid', required: true },
      job_type: { type: 'text', required: true }, // page_insights | post_insights | posts | cm_earnings
      status: { type: 'text', required: false, default: 'pending' }, // pending | running | completed | failed
      started_at: { type: 'timestamptz', required: false, default: null },
      completed_at: { type: 'timestamptz', required: false, default: null },
      error_log: { type: 'text', required: false, default: null },
      // created_at: TIMESTAMPTZ (auto-generated by db)
    }
  }
};

/**
 * Get schema for a specific table
 * @param {string} tableName - Name of the table
 * @returns {object} Schema definition for the table
 */
const getTableSchema = (tableName) => {
  return dbSchema[tableName] || null;
};

/**
 * Get required fields for a table
 * @param {string} tableName - Name of the table
 * @returns {array} Array of required field names
 */
const getRequiredFields = (tableName) => {
  const schema = dbSchema[tableName];
  return schema ? schema.required : [];
};

/**
 * Validate data against schema
 * @param {string} tableName - Name of the table
 * @param {object} data - Data to validate
 * @returns {object} { valid: boolean, errors: array }
 */
const validateData = (tableName, data) => {
  const schema = dbSchema[tableName];
  const errors = [];

  if (!schema) {
    return { valid: false, errors: [`Table schema for '${tableName}' not found`] };
  }

  // Check required fields
  for (const requiredField of schema.required) {
    if (!data.hasOwnProperty(requiredField) || data[requiredField] === undefined || data[requiredField] === null) {
      errors.push(`Required field '${requiredField}' is missing or null`);
    }
  }

  return {
    valid: errors.length === 0,
    errors
  };
};

module.exports = {
  dbSchema,
  getTableSchema,
  getRequiredFields,
  validateData
};
